import "./globals.css";
import { Providers } from "./providers";
import localFont from "next/font/local";

export const metadata = {
  title: "Fok Wai Armed Escort",
  description: "Generated by create next app",
};

const myFont = localFont({ src: "../fonts/SourceHanSerifTC-VF.ttf" });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body className={myFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
